version: '3.8'

services:
  nginx:
    build:
      context: ./lacus-frontend  # 指定构建上下文为 lacus-frontend 目录
    image: eyesmoons/lacus-frontend:1.0.0  # 使用指定的镜像名称
    ports:
      - "8080:8080"  # 将主机的8080端口映射到容器的8080端口
    restart: always  # 容器崩溃时自动重启